stages:
    - release

before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*

release:
    stage: release
    tags:
      - builder
    script:
        - echo $CI_COMMIT_REF_NAME
        - echo $VERSION
        - rm -rf tresorio
        - mkdir tresorio
        - cp -r bundle_modules tresorio/bundle_modules
        - cp -r config tresorio/config
        - cp -r src tresorio/src
        - cp -r __init__.py tresorio/__init__.py
        - cp -r assets tresorio/assets
        - |
          curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
             --data "{ \"tag_name\": \"$VERSION\", \"ref\": \"$CI_COMMIT_REF_NAME\" }" \
             --request POST "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/repository/tags"
        - |
          curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
             --data "{ \"name\": \"$VERSION\", \"tag_name\": \"$VERSION\", \"description\": \"$CI_COMMIT_REF_NAME-[tresorio.zip](https://gitlab.com/tresorio/pablo/-/jobs/$CI_JOB_ID/artifacts/download)\" }" \
             --request POST "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"

    artifacts:
        name: "tresorio-$VERSION"
        paths:
            - tresorio
    only:
      refs:
        - master
        - staging
        - dev
      variables:
        - $VERSION
