stages:
    - release

before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*

release:
    stage: release
    tags:
      - builder
    script:
        - rm -rf tresorio
        - ./build_plugin.sh $CI_COMMIT_REF_NAME
        - ls
        - unzip tresorio.zip
        - |
          curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
             --data "{ \"tag_name\": \"$VERSION\", \"ref\": \"$CI_COMMIT_REF_NAME\" }" \
             --request POST "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/repository/tags"
        - |
          curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
             --data "{ \"name\": \"$VERSION\", \"tag_name\": \"$VERSION\", \"description\": \"$CI_COMMIT_REF_NAME-[tresorio.zip](https://gitlab.com/tresorio/pablo/-/jobs/$CI_JOB_ID/artifacts/download)\" }" \
             --request POST "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"

    artifacts:
        name: "tresorio-$VERSION"
        paths:
            - tresorio
    only:
      refs:
        - master
        - staging
        - dev
      variables:
        - $VERSION
