stages:
    - release

release:
    stage: release
    image: alpine
    script:
        - rm -rf tresorio
        - mkdir tresorio
        - cp -r bundle_modules tresorio/bundle_modules
        - cp -r config tresorio/config
        - cp -r src tresorio/src
        - cp -r __init__.py tresorio/__init__.py
        - cp -r assets tresorio/assets
    artifacts:
        name: "tresorio-$CI_COMMIT_TAG"
        paths:
            - tresorio
    only:
       - tags