name: Release

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  release:
    name: Create releases
    runs-on: [self-hosted, dev]

    steps:
      - uses: actions/checkout@v2

      - name: Build plugin
        run: ./build_plugin.sh ${{ github.ref }}

      - name: Set version
        run: echo ::set-env name=ADDON_RELEASE_VERSION::$(node version.js)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $ADDON_RELEASE_VERSION-${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Release for ${{ github.ref }}, version $ADDON_RELEASE_VERSION
          draft: false
          prerelease: false
